# Generated by Django 4.1.2 on 2022-12-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_post_readers_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='readers',
        ),
        migrations.DeleteModel(
            name='UserPostRelation',
        ),
    ]
